# Generated by Django 6.1 on 2026-10-06 21:41

import secrets

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def give_old_receipts_a_token(apps, schema_editor):
    """Receipts printed before this change get a token too, so a reprint of
    an old receipt carries a working QR code like any other."""
    Sale = apps.get_model("sales", "Sale")
    for sale in Sale.objects.filter(verify_token__isnull=True).only("pk").iterator():
        Sale.objects.filter(pk=sale.pk).update(verify_token=secrets.token_urlsafe(12))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_shift_sale_shift_shift_one_open_shift_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='verify_token',
            field=models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True),
        ),
        migrations.RunPython(give_old_receipts_a_token, migrations.RunPython.noop),
        migrations.CreateModel(
            name='HeldSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('held_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lines', models.JSONField(default=list)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.customer')),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['held_at', 'id'],
            },
        ),
    ]
