# Generated by Django 6.1 on 2026-08-28 13:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Supermarket', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tin', models.CharField(blank=True, max_length=40, verbose_name='TIN / Reg. No.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/')),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, help_text='Set to 0 if the shop does not charge VAT.', max_digits=5)),
                ('receipt_footer', models.CharField(default='Thank you for shopping with us. Goods once sold are not returnable.', max_length=200)),
                ('receipt_width', models.CharField(choices=[('58mm', '58mm thermal roll'), ('80mm', '80mm thermal roll'), ('A4', 'A4 paper')], default='80mm', help_text='Choose A4 if the shop has an ordinary printer.', max_length=10)),
                ('default_reorder_level', models.PositiveIntegerField(default=5, help_text="A product is 'low stock' at or below this, unless it sets its own.")),
                ('expiry_warning_days', models.PositiveIntegerField(default=30, help_text='Warn this many days before an item expires.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop settings',
                'verbose_name_plural': 'Shop settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator (owner / manager)'), ('CASHIER', 'Cashier (seller)')], default='CASHIER', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
