# Generated by Django 6.1 on 2026-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_taken_tour',
            field=models.BooleanField(default=False),
        ),
    ]
