# Generated by Django 6.1 on 2026-10-01 20:52

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_has_taken_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('back_alert_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='closes_at',
            field=models.TimeField(default=datetime.time(22, 0), help_text='After this, silent tills are expected.', verbose_name='Shop closes at'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='hosting_paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='opens_at',
            field=models.TimeField(default=datetime.time(7, 0), help_text='A till that is silent before this is not news.', verbose_name='Shop opens at'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='silence_alert_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Email the owner when no till has reached the system for this many minutes while the shop is open.', verbose_name='Alert after (minutes)'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='summary_sent_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('SIGN_IN', 'Signed in'), ('SIGN_OUT', 'Signed out'), ('SIGN_IN_FAILED', 'Failed sign-in'), ('SALE_VOIDED', 'Sale voided'), ('PRICE_CHANGED', 'Price changed'), ('PRODUCT_DELETED', 'Product deleted / retired'), ('STOCK_ADJUSTED', 'Stock adjusted'), ('STOCK_WRITTEN_OFF', 'Stock written off'), ('STOCK_COUNTED', 'Stock take recorded'), ('DRAWER_HANDED_OVER', 'Drawer handed over'), ('USER_CREATED', 'User added'), ('USER_CHANGED', 'User changed'), ('PASSWORD_RESET', 'Password reset'), ('SETTINGS_CHANGED', 'Shop details changed'), ('BACKUP_DOWNLOADED', 'Data downloaded'), ('TILLS_SILENT', 'Tills went silent'), ('TILLS_BACK', 'Tills back online')], db_index=True, max_length=24)),
                ('summary', models.CharField(max_length=255)),
                ('changes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Till',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_phone', models.BooleanField(default=False)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
