# Generated by Django 6.1 on 2026-10-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_watch_and_audit_trail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('SIGN_IN', 'Signed in'), ('SIGN_OUT', 'Signed out'), ('SIGN_IN_FAILED', 'Failed sign-in'), ('SALE_VOIDED', 'Sale voided'), ('PRICE_CHANGED', 'Price changed'), ('PRODUCT_DELETED', 'Product deleted / retired'), ('STOCK_ADJUSTED', 'Stock adjusted'), ('STOCK_WRITTEN_OFF', 'Stock written off'), ('STOCK_COUNTED', 'Stock take recorded'), ('DRAWER_HANDED_OVER', 'Drawer handed over'), ('USER_CREATED', 'User added'), ('USER_CHANGED', 'User changed'), ('PASSWORD_RESET', 'Password reset'), ('SETTINGS_CHANGED', 'Shop details changed'), ('BACKUP_DOWNLOADED', 'Data downloaded'), ('TILLS_SILENT', 'Tills went silent'), ('TILLS_BACK', 'Tills back online'), ('OTP_SENT', 'Sign-in code sent'), ('OTP_FAILED', 'Wrong sign-in code'), ('OTP_PASSED', 'Sign-in code accepted')], db_index=True, max_length=24),
        ),
    ]
