# Generated by Django 6.1 on 2026-10-02 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('ONLINE', 'Paid online'), ('RECORDED', 'Recorded by CampusNect')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for payment'), ('PAID', 'Paid'), ('FAILED', 'Not paid')], default='PENDING', max_length=8)),
                ('amount', models.PositiveIntegerField(help_text='UGX')),
                ('price_per_page', models.PositiveIntegerField(help_text='UGX a page on the day it was bought - frozen.')),
                ('pages', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('gateway_id', models.CharField(blank=True, max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('audience', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('CODE', 'Sign-in code'), ('ALERT', 'Alert to the owner'), ('BROADCAST', 'Message from the owner')], max_length=10)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('TEST', 'Not sent (test mode)'), ('FAILED', 'Failed'), ('NO_CREDIT', 'Not sent - no SMS credit')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveIntegerField(help_text='UGX, at the current page price')),
                ('gateway_reply', models.CharField(blank=True, max_length=255)),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sms.broadcast')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SignInCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.CharField(blank=True, max_length=200)),
                ('via_owner', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_in_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
